name: Build Check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libjavascriptcoregtk-4.1-dev \
            pkg-config \
            libsoup-3.0-dev \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf \
            rpm \
            dpkg \
            fakeroot \
            cpio

      - name: Install Node dependencies
        run: npm ci

      - name: Build Tauri app
        run: npx tauri build --no-bundle
